# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7506abe88d600ae811a786579500c5ac14353e65d884b0bf8ed17494f5691ef912ea486d71ad20f98f9481e6a0626c9353e9752fb071ae47a42dcd5d03f5ba92

test:
  secret_key_base: 383236e6d6ee94ef8297e52ddccd77cc1d19552e8adcbf22360c0cea98a420725402c1330f1542943a8adf9e0730c09ab4c9e877f9c9f4f3125d97b1404df97d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
